package com.nepalius.location

enum State(val name: String):
  case AL extends State("Alabama")
  case AK extends State("Alaska")
  case AZ extends State("Arizona")
  case AR extends State("Arkansas")
  case CA extends State("California")
  case CO extends State("Colorado")
  case CT extends State("Connecticut")
  case DE extends State("Delaware")
  case DC extends State("District of Columbia")
  case FL extends State("Florida")
  case GA extends State("Georgia")
  case HI extends State("Hawaii")
  case ID extends State("Idaho")
  case IL extends State("Illinois")
  case IN extends State("Indiana")
  case IA extends State("Iowa")
  case KS extends State("Kansas")
  case KY extends State("Kentucky")
  case LA extends State("Louisiana")
  case ME extends State("Maine")
  case MD extends State("Maryland")
  case MA extends State("Massachusetts")
  case MI extends State("Michigan")
  case MN extends State("Minnesota")
  case MS extends State("Mississippi")
  case MO extends State("Missouri")
  case MT extends State("Montana")
  case NE extends State("Nebraska")
  case NV extends State("Nevada")
  case NH extends State("New Hampshire")
  case NJ extends State("New Jersey")
  case NM extends State("New Mexico")
  case NY extends State("New York")
  case NC extends State("North Carolina")
  case ND extends State("North Dakota")
  case OH extends State("Ohio")
  case OK extends State("Oklahoma")
  case OR extends State("Oregon")
  case PA extends State("Pennsylvania")
  case RI extends State("Rhode Island")
  case SC extends State("South Carolina")
  case SD extends State("South Dakota")
  case TN extends State("Tennessee")
  case TX extends State("Texas")
  case UT extends State("Utah")
  case VT extends State("Vermont")
  case VA extends State("Virginia")
  case WA extends State("Washington")
  case WV extends State("West Virginia")
  case WI extends State("Wisconsin")
  case WY extends State("Wyoming")
